/**
 * BaseTemplateMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-18 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.BaseCheckpart;
import com.jfsoft.model.BaseTemplate;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseTemplateMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_TEMPLATE
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_TEMPLATE
     */
    int insert(BaseTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_TEMPLATE
     */
    int insertSelective(BaseTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_TEMPLATE
     */
    BaseTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_TEMPLATE
     */
    int updateByPrimaryKeySelective(BaseTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_TEMPLATE
     */
    int updateByPrimaryKey(BaseTemplate record);



    List<BaseTemplate> getTemplateList();


    BigDecimal getMaxCode();

    List<BaseTemplate> getTemplateByType(String type);
}