/**
 * BaseAreaMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-18 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.BaseArea;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseAreaMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_AREA
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_AREA
     */
    int insert(BaseArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_AREA
     */
    int insertSelective(BaseArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_AREA
     */
    BaseArea selectByPrimaryKey(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_AREA
     */
    int updateByPrimaryKeySelective(BaseArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_AREA
     */
    int updateByPrimaryKey(BaseArea record);
}