/**
 * BaseCheckmethodMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-15 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.BaseCheckmethod;

public interface BaseCheckmethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKMETHOD
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKMETHOD
     */
    int insert(BaseCheckmethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKMETHOD
     */
    int insertSelective(BaseCheckmethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKMETHOD
     */
    BaseCheckmethod selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKMETHOD
     */
    int updateByPrimaryKeySelective(BaseCheckmethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKMETHOD
     */
    int updateByPrimaryKey(BaseCheckmethod record);
}