/**
 * BaseItempartmapMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-15 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.BaseItempartmap;

public interface BaseItempartmapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ITEMPARTMAP
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ITEMPARTMAP
     */
    int insert(BaseItempartmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ITEMPARTMAP
     */
    int insertSelective(BaseItempartmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ITEMPARTMAP
     */
    BaseItempartmap selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ITEMPARTMAP
     */
    int updateByPrimaryKeySelective(BaseItempartmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_ITEMPARTMAP
     */
    int updateByPrimaryKey(BaseItempartmap record);
}