/**
 * BaseCheckpartMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-15 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.BaseCheckpart;

public interface BaseCheckpartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKPART
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKPART
     */
    int insert(BaseCheckpart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKPART
     */
    int insertSelective(BaseCheckpart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKPART
     */
    BaseCheckpart selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKPART
     */
    int updateByPrimaryKeySelective(BaseCheckpart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_CHECKPART
     */
    int updateByPrimaryKey(BaseCheckpart record);
}