/**
 * InsIllnessmapMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-15 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.InsIllnessmap;

public interface InsIllnessmapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INS_ILLNESSMAP
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INS_ILLNESSMAP
     */
    int insert(InsIllnessmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INS_ILLNESSMAP
     */
    int insertSelective(InsIllnessmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INS_ILLNESSMAP
     */
    InsIllnessmap selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INS_ILLNESSMAP
     */
    int updateByPrimaryKeySelective(InsIllnessmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INS_ILLNESSMAP
     */
    int updateByPrimaryKey(InsIllnessmap record);
}