/**
 * InspectPerinfoMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-18 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.InspectPerinfo;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface InspectPerinfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PERINFO
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PERINFO
     */
    int insert(InspectPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PERINFO
     */
    int insertSelective(InspectPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PERINFO
     */
    InspectPerinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PERINFO
     */
    int updateByPrimaryKeySelective(InspectPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PERINFO
     */
    int updateByPrimaryKey(InspectPerinfo record);

    List<InspectPerinfo> getPerinfoList();

    List<InspectPerinfo> getPerinfoDetail(Map<String,Object> params);
}