/**
 * InspectPicresultMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-15 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.InspectPicresult;

public interface InspectPicresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PICRESULT
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PICRESULT
     */
    int insert(InspectPicresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PICRESULT
     */
    int insertSelective(InspectPicresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PICRESULT
     */
    InspectPicresult selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PICRESULT
     */
    int updateByPrimaryKeySelective(InspectPicresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECT_PICRESULT
     */
    int updateByPrimaryKey(InspectPicresult record);
}