/**
 * OutPerinfoMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-18 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.OutPerinfo;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutPerinfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int insert(OutPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int insertSelective(OutPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    OutPerinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int updateByPrimaryKeySelective(OutPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int updateByPrimaryKey(OutPerinfo record);
}