/**
 * OutPerinfoMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-15 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.OutPerinfo;

public interface OutPerinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int insert(OutPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int insertSelective(OutPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    OutPerinfo selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int updateByPrimaryKeySelective(OutPerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUT_PERINFO
     */
    int updateByPrimaryKey(OutPerinfo record);
}