/**
 * SysActormenumapMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-18 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.SysActormenumap;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysActormenumapMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORMENUMAP
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORMENUMAP
     */
    int insert(SysActormenumap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORMENUMAP
     */
    int insertSelective(SysActormenumap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORMENUMAP
     */
    SysActormenumap selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORMENUMAP
     */
    int updateByPrimaryKeySelective(SysActormenumap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORMENUMAP
     */
    int updateByPrimaryKey(SysActormenumap record);
}