/**
 * SysActordeptmapMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-18 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.SysActordeptmap;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysActordeptmapMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORDEPTMAP
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORDEPTMAP
     */
    int insert(SysActordeptmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORDEPTMAP
     */
    int insertSelective(SysActordeptmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORDEPTMAP
     */
    SysActordeptmap selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORDEPTMAP
     */
    int updateByPrimaryKeySelective(SysActordeptmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTORDEPTMAP
     */
    int updateByPrimaryKey(SysActordeptmap record);
}