/**
 * SysActorMapper.java
 * Copyright© 2017 北京金风易通科技有限公司
 * All rights reserved.
 * -----------------------------------------------
 * 2017-08-15 Created
 */
package com.jfsoft.mapper;

import com.jfsoft.model.SysActor;

public interface SysActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTOR
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTOR
     */
    int insert(SysActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTOR
     */
    int insertSelective(SysActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTOR
     */
    SysActor selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTOR
     */
    int updateByPrimaryKeySelective(SysActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACTOR
     */
    int updateByPrimaryKey(SysActor record);
}